name: cozy_home_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/appartments/
    - assets/images/bathrooms/
    - assets/images/bedrooms/
    - assets/images/kitchens/
    - assets/images/logos/
    - assets/icon.png

